import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // serverSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  mobileSidebar: [{type: 'autogenerated', dirName: 'docs-mobile'}],
  serverSidebar: [
    'manual_ordering/ALARMiator Probieren/index',
      {
        type: 'category',
        label: 'Getting Started',
        collapsible: true,
        collapsed: false,
        items: [
          'manual_ordering/Getting Started/index',
          'manual_ordering/Getting Started/Übersicht-Erstinstallation',
          'manual_ordering/Getting Started/NginxProxyManagerVerschlüsseln',
        ],
      },
    'manual_ordering/alternativereverseproxies/index',
    {type: 'autogenerated', dirName: 'automatic_ordering'}
  ],
};

export default sidebars;
